# Age-structured population model

## Continuous time model

In the previous chapter we structured the population by a discrete variable, the sex of the individuals. This gave rise to a system of coupled ODEs, one ODE for each class of individuals. In this section we will structure the population by a continuous variable, the age of the individuals. This will give rise to a partial differential equation (PDE) for the age-dependent population density. We will solve this PDE and study the long-term behaviour of the population and its age distribution.

So instead of describing the population just by the total number of individuals $N(t)$, we will describe it by the density $n(t,a)$ of individuals at age $a$. The total number $N(t)$ of individuals in the population  is then given by the integral of $n(t,a)$ over all ages. More generally, the total number of individuals in the population that are between age $a_1$ and $a_2$ is given by the integral of $n(t,a)$ over the interval $[a_1,a_2]$. You are familiar with the concept of density from probability theory, where continuous random variables are described by a probability density rather than a probability. You may also be familiar with the concept from physics, where the density of a material describes how the mass is distributed over space. Here, the density $n(t,a)$ describes how the individuals are distributed over ages.

To derive the PDE for the age-structured population density, we consider how the density changes over an infinitesimal time interval $\delta t$ due to deaths:
$$
n(t+\delta t, a+\delta t) = n(t,a) - \mu(a) n(t,a) \delta t.
$$ {#eq-a1}
Note how we had to take into account that over the time interval $\delta t$ the age of the individuals has increased by $\delta t$. We now Taylor-expand the left-hand side around $t$ and $a$:
$$
n(t+\delta t, a+\delta t) = n(t,a) + \frac{\partial n}{\partial t} \delta t + \frac{\partial n}{\partial a} \delta t + \mathcal{O}(\delta t^2).
$$ {#eq-a2}
Cancelling the $n(t,a)$ terms on both sides and dividing by $\delta t$ gives us the PDE for the age-structured population density:
$$
\frac{\partial n}{\partial t} + \frac{\partial n}{\partial a} = -\mu(a) n.
$$ {#eq-a3}

This equation captures the effect of individuals aging and dying, but it does not capture how they are born. Individuals are born with age $0$. These offspring can be produced by parents of any ages, but with an age-dependent rate $b(a)$. This gives
$$
n(t,0) = \int_0^\infty b(a) n(t,a) \, da.
$$ {#eq-a4}
This is a boundary condition for the PDE. It says that the density of individuals at age $0$ is given by the total number of offspring produced by the individuals of all ages. 

We will now solve the PDE for the age-structured population density by the method of separation of variables. We will make the Ansatz $n(t,a) = f(t) r(a)$. You have seen this trick for finding solutions of linear, homogeneous PDEs in other modules, like Waves and Fluids for example. Substituting this Ansatz into the PDE gives
$$
f'(t) r(a) + f(t) r'(a) = -\mu(a) f(t) r(a).
$$ {#eq-a5}
Dividing by $f(t) r(a)$ gives
$$
\frac{f'(t)}{f(t)} + \frac{r'(a)}{r(a)} = -\mu(a).
$$ {#eq-a6}
We now collect all terms that depend on $t$ on the left-hand side and all terms that depend on $a$ on the right-hand side:
$$
\frac{f'(t)}{f(t)} = - \frac{r'(a)}{r(a)} - \mu(a).
$$ {#eq-a7}
Because the left-hand side is independent of $a$ and the right-hand side is independent of $t$, both sides must be equal to a constant. We introduce the separation constant $\gamma$ and write
$$
\frac{f'(t)}{f(t)} = \gamma, \quad \frac{r'(a)}{r(a)} = -\gamma - \mu(a).
$$ {#eq-a8}
These are now linear ODEs and hence easy to solve. The first ODE has the solution 
$$
f(t) = f(0) e^{\gamma t}
$$ {#eq-a9}
and the second ODE has the solution
$$
r(a) = r(0) \exp\left(-\int_0^a \mu(a') \, da'-\gamma a\right).
$$  {#eq-a10}

So altogether we have the population density
$$
n(t,a) = n(0,0) e^{\gamma t} \exp\left(-\int_0^a \mu(a') \, da'-\gamma a\right),
$$ {#eq-a11}
where $n(0,0)=f(0)r(0)$ is the initial density of individuals at age $0$. 

So far we don't yet know the value of the separation constant $\gamma$. This will be determined by the boundary condition. If we substitute the solution @eq-a11 into the boundary condition @eq-a4, we get
$$
n(0,0)e^{\gamma t} = \int_0^\infty b(a) n(0,0)e^{\gamma t} \exp\left(-\int_0^a \mu(a') \, da'-\gamma a\right)\, da.
$$ {#eq-a12}
We can cancel the common factor $n(0,0)e^{\gamma t}$ on both sides to get the condition
$$
1= \int_0^\infty b(a) \exp\left(-\int_0^a \mu(a') \, da'-\gamma a\right) \, da = \phi(\gamma).
$$ {#eq-a13}
We have introduced the shorthand notation $\phi(\gamma)$ for the integral on the right-hand side. The condition @eq-a12 is a transcendental equation for $\gamma$. We cannot solve it analytically for $\gamma$. But we observe that $\phi$ is a monotonically decreasing function of $\gamma$. This observation alone allows us to make a statement about the sign of $\gamma$. According to @eq-a9 the sign of $\gamma$ determines whether the total population grows expnentially or goes extinct.

If $\gamma$ is positive, then the monotonicity of $\phi$ tells us that $\phi(0) > \phi(\gamma)  = 1$ and vice versa. Conversely, if $\gamma$ is negative, then $\phi(0) < \phi(\gamma) = 1$ and vice versa. So to determine the sign of $\gamma$ we only have to look at the value of
$$
\phi(0) = \int_0^\infty b(a) \exp\left(-\int_0^a \mu(a') \, da'\right)\, da.
$$ {#eq-a14}

* If $\phi(0) > 1$, then  $\gamma > 0$ and the population grows exponentially.

* If $\phi(0) < 1$, then $\gamma < 0$ and the population goes extinct.

This result actually has a very intuitive explanation. The factor
$$
\exp\left(-\int_0^a \mu(a') \, da'\right)=:l(a)
$$ {#eq-a15}
is the probability that an individual survives up to age $a$. Therefore $\phi(0)$ is the expected number of offspring produced by an individual during its lifetime. If this number is greater than $1$, then the population grows exponentially. If it is less than $1$, then the population goes extinct.


## Discrete time model

In the continuous-time age-structured population model discussed in the previous section we had assumed that births take place continuously through time. If however reproduction is an annual event, taking place in a short breeding season for example, then it is more natural to model the population in discrete time. We will now derive the discrete-time version of the age-structured population model and then study the long-term behaviour of the population and its age distribution.

### Model description

Both time and age will be discrete variables. We will take them to be integers counting years. We will describe the population by the numbers $N_{a,t}$ of individuals of age $a$ at time $t$. The total number $N_t$ of individuals in the population at time $t$ is then given by the sum of $N_{a,t}$ over all ages.

The parameters of our model will be the probabilities $S_a$ of surviving from age $a-1$ to age $a$ and the number of offspring $b_a$ produced by an individual when they reach age $a$. Because the number of individuals at age $a$ at time $t+1$ is the number of individuals that a year earlier were at age $a-1$ and have survived to age $a$, we have
$$
N_{a,t+1} = S_{a} N_{a-1,t}.
$$ {#eq-a16}
When individuals reach age $a$, they each produce $b_a$ offspring. The total number of offspring produced at time $t$ is therefore given by
$$
N_{0,t} = \sum_{a=1}^\infty b_a N_{a,t}.
$$ {#eq-a17}
This is a boundary condition for the discrete-time model. It says that the number of individuals at age $0$ at time $t$ is given by the total number of offspring produced by the individuals of all ages at time $t$. This is the discrete-time analogue of the boundary condition @eq-a4 for the continuous-time model.

Note that in @eq-a17 both sides of the equation are at time $t$. That is because reproduction is taken to happen instantaneously at time $t$. It is conventional to use @eq-a16 to rewrite the boundary condition @eq-a17 as an equation for $N_{0,t+1}$:
$$
N_{0,t+1} = \sum_{a=1}^\infty b_a N_{a,t+1}= \sum_{a=1}^\infty b_a S_{a} N_{a-1,t}
= \sum_{a=1}^\infty F_{a-1} N_{a-1,t},
$$ {#eq-a18}
where we have introduced the fecundity $F_a:=b_{a+1} S_{a+1}$.

@eq-a16 and @eq-a18 are the equations for the discrete-time age-structured population model. They are a system of coupled difference equations, one equation for each age class. We would like to solve them to determine the numbers $N_{a,t}$ of individuals at each age at each time. Notice that @eq-a16 looks very simple and we could use it to determine $N_{a,t}$ for $a=1,2,3,\ldots$ in terms of $N_{0,t}$,
$$
\begin{split}
N_{a,t} &= S_{a} N_{a-1,t} = S_{a} S_{a-1} N_{a-2,t} = \cdots \\
&= S_aS_{a-1}\cdots S_1 N_{0,t}
= l_{a} N_{0,t},
\end{split}
$$ {#eq-ac18}
where we used that the product $S_aS_{a-1}\cdots S_1$ is the probability of surviving from age $0$ to age $a$, which we denote by $l_a$. However @eq-a18 spoils the game because it tells us that we won't know $N_{0,t}$ until we know $N_{a,t}$ for all ages $a$. This is a typical feature of age-structured population models. The number of individuals at age $0$ at time $t$ depends on the number of individuals at all other ages at time $t$. Solving both @eq-a16 and @eq-a18 together is a non-trivial task.

### Stable age distribution
In analogy to the continuous-time model, we will now look for a solution of the form
$$
N_{a,t} = \lambda^t r(a)
$$ {#eq-ab19}
This is a solution in which the age distribution $r(a)$ remains stable from one year to the next, but the total population grows or shrinks by a factor $\lambda$ each year. 
This means in particular that for this solution $N_{a,t+1} = \lambda N_{a,t}$ for all ages $a$. For $a=1$ this gives
$$
N_{1,t+1} = \lambda N_{1,t} = S_1 N_{0,t}
$$ {#eq-a23}
and hence
$$
N_{1,t} = \frac{S_1}{\lambda} N_{0,t}.
$$ {#eq-a24}
Similarly we can express $N_{2,t}$ in terms of $N_{0,t}$:
$$
N_{2,t} = \frac{S_2}{\lambda} N_{1,t} = \frac{S_1 S_2}{\lambda^2} N_{0,t}.
$$ {#eq-a25}
We can continue this process to express $N_{a,t}$ in terms of $N_{0,t}$:
$$
N_{a,t} = \frac{S_1 S_2 \cdots S_{a}}{\lambda^a} N_{0,t}= \frac{l_{a}}{\lambda^a} N_{0,t}.
$$ {#eq-a26}


Finally, for the newborns we have
$$
N_{0,t+1} = \lambda N_{0,t} = \sum_{a=1}^M F_{a-1} N_{a-1,t} = \sum_{a=1}^M F_{a-1} \frac{l_{a-1}}{\lambda^{a-1}} N_{0,t}.
$$ {#eq-a27}
Dividing the equation by $\lambda N_{0,t}$ gives
$$
1 = \sum_{a=1}^M F_{a-1}\frac{l_{a-1}}{\lambda^a}.
$$ {#eq-a28}
Using that $F_{a-1} = b_{a} S_{a}$ and $S_al_{a-1}=l_a$ we can rewrite this equation as
$$
1 = \sum_{a=1}^M b_a \,l_a\,\lambda^{-a} =:\psi(\lambda).
$$ {#eq-a29}
This is the Euler-Lotka equation for the stable age distribution. Compare it to the corresponding equation for the continuous-time model @eq-a13 with $e^{\gamma}=\lambda$. The only difference is that the continuous-time model has an integral over age, while the discrete-time model has a sum over age.

By the same argument as in the continuous case we can see that if the expected number of offspring produced by an individual during its lifetime, $\sum_{a=1}^M b_a \,l_a=\psi(1)$, is greater than $1$ then the population grows exponentially. If it is less than $1$, then the population goes extinct.

We will now determine the stable age distribution for a specific example.

::: {#exm-spotted_owl}
For the spotted owl the age-dependent reproduction numbers are
$$
b_a = \begin{cases}
0 & \text{if } a < 2, \\
b & \text{if } a \geq 2
\end{cases}
$$ {#eq-a30}
for some constant $b$. The age-dependent survival probabilities are
$$
S_a = \begin{cases}
1 & \text{if } a = 1, \\
l & \text{if } a = 2, \\
p & \text{if } a > 2
\end{cases}
$$ {#eq-a31}
for some constants $l$ and $p$. Those values of the survival probabilities from year to year lead to the following values of the survival probabilities from birth to age $a$:
$$
l_a = \begin{cases}
1 & \text{if } a = 1, \\
l\, p^{a-2} & \text{if } a \geq 2.
\end{cases}
$$ {#eq-a32}
Substituting these values into the expression for $\psi(\lambda)$ in @eq-a29 gives
$$
\begin{split}
\psi(\lambda) &= b l \sum_{a=2}^\infty p^{a-2} \lambda^{-a} = lb\lambda^{-2}\sum_{n=0}^\infty \frac{p}{\lambda}\\
&= lb\lambda^{-2}\frac{1}{1-\frac{p}{\lambda}}
=\frac{lb}{\lambda(\lambda-p)},
\end{split}
$$ {#eq-a33}
where we made use of the formula for a geometric series, valid if $|p/\lambda|<1$ ^[If $\lambda\geq p$, then $\psi(\lambda)$ diverges and does not satisfy the Euler-Lotka equation $\psi(\lambda)=1$.]. 
In particular, the expected number of offspring produced by an individual in their lifetime is $$
\psi(1)=lb/(1-p).
$$
If this is greater than $1$, then the population grows exponentially. If it is less than $1$, then the population goes extinct.


In this case the Euler-Lotka equation $\psi(\lambda)=1$ becomes the quadratic equation for $\lambda$:
$$
\psi(\lambda)=\frac{lb}{\lambda(\lambda-p)}=1 \quad \Leftrightarrow \quad \lambda^2 - \lambda p - lb = 0.
$$ {#eq-a34}
The solutions are
$$
\lambda_\pm = \frac{p \pm \sqrt{p^2 + 4lb}}{2}.
$$ {#eq-a35}
We are interested in the positive solution $\lambda_+$. 
Substituting this value for $\lambda$ back into @eq-a26 and @eq-ab19 we see that we have found the solution
$$
N_{a,t} = \left(\frac{p + \sqrt{p^2 + 4lb}}{2}\right)^{t-a}l_a N_{0,0}
$$ {#eq-a36}
for any choice of $N_{0,0}$.

:::

### Leslie matrix

In the case where there is a maximal age $m$ beyond which there is no reproduction, either because $b_a = 0$ for $a>m$ or because there are not older individuals because $S_{m+1} = 0$, we can then collect the equations for $N_{a,t+1}$ for $a=0,1,2,\ldots,m-1$ (@eq-a16 and @eq-a18) into a matrix equation:

$$
\begin{pmatrix}
N_{0} \\
N_{1} \\
N_{2} \\
\vdots \\
N_{m-1}
\end{pmatrix}_{t+1}
=
\begin{pmatrix}
F_0 & F_2 & \cdots & F_{m-2} & F_{m-1} \\
S_1 & 0 & \cdots & 0 & 0 \\
0 & S_2 & \cdots & 0 & 0 \\
\vdots & \vdots & \ddots & \vdots & \vdots \\
0 & 0 & \cdots & S_{m-1} & 0
\end{pmatrix}
\begin{pmatrix}
N_{0} \\
N_{1} \\
N_{2} \\
\vdots \\
N_{m-1}
\end{pmatrix}_{t}.
$$ {#eq-a19}

Note that we did not need to include the equation for $N_{m,t+1}$ in the matrix equation because $N_{m,t+1}$ is not needed to calculate the reproduction. Once the matrix equation @eq-a19 is solved, we can determine $N_{m,t+1}$ separately from @eq-a16 if we are interested, and similarly for all older age classes that do not reproduce, if any.

The matrix on the right-hand side of @eq-a19 is a so-called Leslie matrix. Let us denote it by $L$. The equation @eq-a19 is a matrix equation of the form
$$
\mathbf{N}_{t+1} = L\, \mathbf{N}_t,
$$ {#eq-a20}
where $\mathbf{N}_t$ is the column vector of the numbers $N_{a,t}$ and $L$ is the Leslie matrix. 

We now have the task of solving the homogeneous linear difference equation @eq-a20 with constant coefficients (the Leslie matrix $L$ does not depend on time). You know from earlier modules that when confronted with a homogeneous linear _differential_ equation with constant coefficients you can solve it with an exponential Ansatz. The same works for linear difference equations. We make the Ansatz
$$
\mathbf{N}_t = \lambda^t \mathbf{v}
$$ {#eq-a21}
and substitute it into @eq-a20. This gives
$$
\lambda^{t+1} \mathbf{v} = L \lambda^t \mathbf{v}.
$$ {#eq-a22}
Dividing by $\lambda^t$ gives
$$
\lambda \mathbf{v} = L \mathbf{v}.
$$ {#eq-a23}
This means that our Ansatz works if we choose $\lambda$ to be an eigenvalue of the Leslie matrix $L$ and $\mathbf{v}$ to be the corresponding eigenvector. 

In the case where all eigenvalues of the Leslie matrix are distinct^[In the case where there are repeated eigenvalues, the general solution is just a bit more complicated. Luckily in ecology, we are rarely interested in that case, because the probability that a real ecosystem is exactly so that this special case arises is zero.], the general solution is the linear combination of the solutions for each eigenvalue.
$$
\mathbf{N}_t = c_1 \lambda_1^t \mathbf{v}_1 + c_2 \lambda_2^t \mathbf{v}_2 + \cdots + c_m \lambda_m^t \mathbf{v}_m,
$$ {#eq-a24}
where $\lambda_1,\lambda_2,\ldots,\lambda_m$ are the eigenvalues of the Leslie matrix and $\mathbf{v}_1,\mathbf{v}_2,\ldots,\mathbf{v}_m$ are the corresponding eigenvectors. The constants $c_1,c_2,\ldots,c_m$ are determined by the initial conditions.

::: {#exm-leslie1}

Consider a population with the reproduction numbers $b_a$ and the survival probabilities $S_a$ given in the following table:

| $a$ | $b_a$ | $S_a$ | $F_a$ |
| --- | ----- | ----- | ----- |
| 0   | 0     | ---   |  0    |
| 1   | 0     |  1    |  1/2  |
| 2   | 1     |  1/2  |  1    |
| 3   | 2     |  1/2  |  0    | 
| 4   | 0     |  1/2  |  0    |

The final column in that table is calculated from the previous ones using $F_a:=b_{a+1}S_{a+1}$. In this example the maximum age $m$ beyond which there is no reproduction is $m=3$. Hence the corresponding Leslie matrix is a $3\times 3$ matrix. It is given by
$$
L = \begin{pmatrix}
F_0&F_1&F_2 \\
S_1 & 0 & 0 \\
0 & S_2 & 0
\end{pmatrix}=\begin{pmatrix}
0 & 1/2 & 1 \\
1 & 0 & 0 \\
0 & 1/2 & 0
\end{pmatrix}.
$$ {#eq-a25}

Assume that the at time $t=0$ we only have 10 individuals all of age 0, i.e.,
$$
\mathbf{N}_0 = \begin{pmatrix}
10 \\
0 \\
0
\end{pmatrix}.
$$ {#eq-a26}
We can then calculate the numbers at the following times $t=1,2,3,\ldots$ by repeated multiplication by the Leslie matrix $L$:
$$
\mathbf{N}_1 = L \mathbf{N}_0 = \begin{pmatrix}
0 & 1/2 & 1 \\
1 & 0 & 0 \\
0 & 1/2 & 0
\end{pmatrix}
\begin{pmatrix}
10 \\
0 \\
0 
\end{pmatrix}
= \begin{pmatrix}
0 \\
10 \\
0
\end{pmatrix},
$$
$$
\mathbf{N}_2 = L \mathbf{N}_1
= \begin{pmatrix}
5 \\
0 \\
5
\end{pmatrix}, 
~~~
\mathbf{N}_3 = L \mathbf{N}_2 = \begin{pmatrix}
5 \\
5 \\
0
\end{pmatrix}, \cdots.
$$
Continuing like this (using a computer) we observe that the population converges to a stable age distribution. 
$$
\lim_{t\to\infty}\mathbf{N}_t = \begin{pmatrix}
4 \\
4 \\
2
\end{pmatrix}.
$$ {#eq-a27}

To understand this phenomenon we look for the eigenvalues and eigenvectors of the Leslie matrix. The eigenvalues are the solutions of the characteristic equation
$$
\begin{split}
0&=\det(L-\lambda I)=\begin{vmatrix}
-\lambda & 1/2 & 1 \\
1 & -\lambda & 0 \\
0 & 1/2 & -\lambda
\end{vmatrix}
= -\lambda^3 + \frac{1}{2}\lambda+\frac12\\
&= (1-\lambda)\left(\lambda^2+\lambda+\frac12\right)
\end{split}
$$ {#eq-a29}
We can read off that the solutions are
$$
\lambda_) = 1, \quad \lambda_\pm = -\frac{1}{2} \pm \frac{1}{2}i.
$$ {#eq-a30}
Because the magnitude of the eigenvalues $\lambda_\pm$ is less than $1$, we have that $\lim_{t\to\infty}\lambda_\pm^t=0$. This means that the stable age distribution is given by the eigenvector corresponding to the eigenvalue $\lambda_0=1$:
$$
\lim_{t\to\infty}\mathbf{N}_t = \lim_{t\to\infty}\left(c_0 \lambda_0^t \mathbf{v}_0 + c_+ \lambda_+^t \mathbf{v}_+ + c_- \lambda_-^t \mathbf{v}_-\right) = c_0 \mathbf{v}_0.
$$
:::

In general, if the Leslie matrix has a unique dominatn eigenvalue $\lambda_0$ with a corresponding eigenvector $\mathbf{v}_0$, then 
$$
\lim_{t\to\infty}\frac{\mathbf{N}_t}{\lambda_0^t} = c_0 \mathbf{v}_0,
$$
where $c_0$ is a constant that depends on the initial conditions. This means that the population converges to a stable age distribution. The stable age distribution is given by the eigenvector corresponding to the dominant eigenvalue of the Leslie matrix.

Luckily, there is a theorem about the eigenvalues and eigenvectors of non-negative matrices that we can use to determine whether a Leslie matrix has a unique dominant eigenvalue. We start by associating the Leslie matrix with a directed graph. The graph has $m$ vertices and a directed edge from vertex $i$ to vertex $j$ if and only if the Leslie matrix has a non-zero entry in column $i$ and row $j$. The graph is called the Leslie graph. We call the Leslie matrix irreducible if its Leslie graph is strongly connected, which means that there is a directed path between any two nodes. We call the Leslie matrix primitive if the greatest common divisor of the lengths of all circuits in the Leslie graph is $1$. The following theorem is then true:

::: {#thm-leslie}
If the Leslie matrix is irreducible and primitive, then it has a unique dominant eigenvalue that is real and positive. The corresponding right eigenvector is real and strictly positive.
:::

This is a special case of the Perron-Frobenius theorem, which is a general theorem about non-negative matrices, and is used extensively in the theory of Markov chains. The above theorem is exactly what we need, because it tells us when the Leslie matrix has a unique dominant eigenvalue and a corresponding eigenvector that gives the stable age distribution.


## Exercises

### Continuous time

#### * Age-independent rates
::: {#exr-age_structured}
In the continuous-time age-structured population model consider the case where $b(a)=b$
and $\mu(a)=\mu$ are both constant. Repeat all steps of the analysis but simplifying the expressions at each step by using the constant values for birth and death rates.

1. Solve the partial differential
equation of the age-structured model by making the Ansatz $n(t,a)=f(t)r(a)$ and introducing the separation constant $\gamma$.
2. Use the boundary condition at $a=0$ to determine the value of $\gamma$.
3. Give the condition under which the population goes extinct and compare it to the condition in the exponential model from chapter 1.
:::

#### o Harvestings an age-structured population
::: {#exr-age_harvesting}
Consider an age-structured fish population in which all individuals above the maturity age $a_m$ are reproducing, at a fixed rate, so that
$$
b(a) = \begin{cases}
0 & \text{if } a < a_m, \\
b & \text{if } a \geq a_m.
\end{cases}
$$ {#eq-age_harvesting_1}
All fish at all ages experience a natural death rate $\mu_0$. In addition, fish above the maturity size are harvested at a constant rate $\mu_F$, so that
$$
\mu(a) = \begin{cases}
\mu_0 & \text{if } a < a_m, \\
\mu_0 + \mu_F & \text{if } a \geq a_m.
\end{cases}
$$ {#eq-age_harvesting_2}
By calculating the expected number of offspring per individual, determine the limit on the harvesting rate $\mu_F$ that allows the population to be sustainable.
:::


#### Seasonal mortality
::: {#exr-seasonal_mortality}
Consider an age-structured population model in which, in addition to an
age-dependent mortality, there is also a seasonal mortality. The population
is described by a function $n(t,a)$ giving the density of individuals of age
$a$ at time $t$ which satisfies  the equations
$$
\partial_t n(t,a)+\partial_a n(t,a)=-(\mu(a)+m(t))\,n(t,a),
$$ {#eq-sma1}
$$
n(t,0) = \int_0^\infty b(a) n(t,a) da.
$$ {#eq-sma2}
The birth rate $b(a)$ and the mortality rates $\mu(a)$ and $m(t)$ are
all positive.

(a) By substituting the ansatz
$n(t,a)=p(t)r(a)$ into equation @eq-sma1 and separating variables
with a separation constant $\gamma$, derive solutions for
$p(t)$ and $r(a)$ and hence for $n(t,a)$, involving $\gamma$.

(b) By substituting your solution from part (a) into equation @eq-sma2,
derive an equation for $\gamma$. Write this in the form $\phi(\gamma)=1$ for
some function $\phi$. Show that this $\phi$ is a monotonic function.

(c) Assume that the seasonal mortality rate $m(t)$ is periodic  with period $1$
and denote by $F$ the averaged seasonal mortality. By considering the
population at the end of each season, show that the population
will go extinct if $\gamma <F$.

(d) Explain how you can use a property of the function $\phi$ to eliminate
$\gamma$ from the condition for extinction. Thus finally give the
condition for extinction in terms of $b(a), \mu(a)$ and $F$.
:::

### Discrete time

#### * Fibonacci population
::: {#exr-leslie}
Consider a population in which individuals on average produce one offspring when they turn 1 year old and another offspring when they turn 2 years old. After that they die. Assume that there is no mortality before they turn 2 year old.

1. Formulate the above information in terms of values for the reproduction numbers $b_a$ and the survival probabilities $S_a$.
1. Write down the Leslie matrix for this population.
2. Assume that at $t=0$ we start with 1 individual of age 0. By hand, calculate the numbers of individuals at each age at time $t=1,2,3,4$ and $5$. 
3. Using the Leslie matrix, calculate the stable age distribution and the long-term growth factor (the factor by which the total population changes from one year to the next).

:::

#### Semelparous population
::: {#exr-semelparous}
Consider a population in which individuals die after having given birth for the first time at age 3. The life history parameters are given by the following table:

| $a$ | $b_a$ | $S_a$ |
| --- | ----- | ----- |
| 1   | 0     |  1    |
| 2   | 0     |  1/2  |
| 3   | 6     |  1/3  |

1. Calculate the Leslie matrix for this population.

2. Assume that at $t=0$ we start with 10 individual, all of age 0. Use the Leslie matrix to calculate the numbers of individuals of ages $0,1,2$ at times $t=1,2,3$. What will happen in the long run? Will the population evolve towards a stable age distribution?

3. Draw the graph associated with the Leslie matrix and determine whether the Leslie matrix is irreducible and primitive. 
:::

#### Eastern Screech Owl
::: {#exr-owl}
This exercise is most suitable for you if you are willing to use a computer to find eigenvalues and eigenvectors of matrices. 

The Eastern Screech Owl is a small owl that is found in the eastern United States and Canada. It is a cavity-nesting bird, which means that it nests in holes in trees. It is able to adapt to diverse habitats, including wooded residential neighbourhoods and parks in suburban areas. In suburban areas, these owls find a variety of nesting opportunities, such as tree cavities, nest boxes, and even abandoned buildings, which may be less available in intensively farmed rural areas or dense forests. Additionally, the suburban settings can offer a rich supply of prey, including insects, small mammals, and other small creatures, partly due to the lower prevalence of large predators.

Below is a life table collected for two different habitats, suburban and rural, in Texas. 

| Age | Suburban     |           | Rural        |           |
| --- | ------------ | --------- | ------------ | --------- |
| $a$ |   $l_a$      |   $b_a$   |   $l_a$      |   $b_a$   |
| 0   | 1.00         | 0.0       | 1.00         | 0.0       |
| 1   | 0.49         | 0.8       | 0.30         | 0.8       |
| 2   | 0.18         | 1.3       | 0.11         | 1.1       |
| 3   | 0.10         | 1.5       | 0.06         | 1.6       |
| 4   | 0.06         | 1.6       | 0.04         | 1.0       |
| 5   | 0.04         | 1.3       | 0.02         | 1.0       |
| 6   | 0.03         | 1.3       |              |           |
| 7   | 0.02         | 1.3       |              |           |
| 8   | 0.02         | 1.3       |              |           |
| 9   | 0.01         | 1.3       |              |           |
| 10  | 0.01         | 1.3       |              |           |


For each of the two populations do the following:

1. Calculate the reproductive number, i.e., the expected number of offspring produced by a single individual during its lifetime.
2. Calculate the Leslie matrix. Note that the table gives the survival probabilities $l_a$ from birth to age $a$ instead of the yearly survival probabilities $S_a$. The yearly survival probabilities can be calculated from the life table by $S_a = l_a/l_{a-1}$.
3. Use the Leslie matrix to calculate the stable age distribution and the long-term growth factor (the factor by which the total population changes from one year to the next).
4. Calculate the average age in the stable age distribution as well as the average age of parents of newborns.

:::

