# Problem sheet 1 {.unnumbered}

Exercises marked with a * are essential and are to be handed in. Exercises marked with a + are important and you are urged to complete them. Other exercises are optional but recommended.

The * and + markup will only be applied to exercises once the material you need to solve them has been covered in the lectures.

#### *Sketching solutions
::: {#exr-sketch_solutions}
Consider the population model with carrying capacity and Allee effect given by the differential equation
$$\frac{dN}{dt}=rN\left(1-\frac{N}{K}\right)\left(\frac{N}{K_0}-1\right).$$
Here $r>0$, $K>K_0>0$ are constants. Simply by considering the shape of the right hand side, sketch a graph with several solutions for different initial conditions. Choose two initial conditions between $0$ and $K_0$, two initial conditions between $K_0$ and $K$ and one initial condition larger than $K$. Note that the graph only needs to be qualitatively correct, similar to the rough sketch for the solutions of the logistic model sketched in the first lecture.
:::

#### +Von Bertalanffy growth
::: {#exr-vonBertalanffy_growth}
Assume the weight $w(t)$ of an individual fish at time $t$ is
governed by the differential equation
$$\frac{dw}{dt}=\alpha\,w^{2/3}-\beta w$$
with initial condition $w(0)=w_0$ (the weight at birth), and where
$\alpha$ and $\beta$ are positive parameters depending on the fish species.

i) Without solving the differential equation, just thinking about fixed points and their stability, determine $\lim_{t\rightarrow\infty}w(t)$.

ii) Derive the linear first order ODE for $u=w^{1/3}$ and solve it.

iii) Use the solution for $u$ to find the solution for $w$.
:::


#### Solving logistic equation
::: {#exr-logistic_solution}
By using separation of variables and partial fractions, solve the logistic equation
$$\frac{dN}{dt}=rN\left(1-\frac{N}{K}\right)$$
with initial condition $N(0)=N_0$.
:::


#### Harvesting with fixed effort
::: {#exr-harvest_effort}
Consider a population $N(t)$ that is described by the logistic model with carrying capacity $K$ and initial growth rate
$r$. You want to harvest this population, for example
by hunting or fishing, with some effort $E$. The rate at which you harvest individuals (which removes them from
the population and hence results in an additional source of death) is proportional to the size of the population:
$H = E N$. This is called the yield.  Write down the differential equation for $N(t)$ including this harvesting term. Determine the
fixed points and their stability. Find the maximum sustainable harvest rate $H$, i.e., the maximum harvest rate that can be sustained indefinitely.
:::

#### Harvesting with fixed quota
::: {#exr-harvest_quota}
As in @exr-harvest_effort, consider a population $N(t)$ that is described by the logistic model with carrying capacity $K$ and initial growth rate
$r$. Imagine that this describes a fish population in a lake where fishing is going to be introduced, and that you are tasked with setting the quota that 
limits the rate at which the fishers are allowed to take fish out of the lake. The fishers demand that you set the quota to the
maximum sustainable level. What is the maximum sustainable quota according to the model? Would it be wise to give in to the demand of
the fishers and set the quota at this level?
:::

#### Harvesting in Gompertz model
::: {#exr-gompertz}
Repeat exercises [-@exr-harvest_effort] and [-@exr-harvest_quota] but with the logistic model replaced by the Gompertz model
$$
\frac{dN}{dt} = \alpha N \log\frac{K}{N},
$$
where $\alpha$ and $K$ are positive constants.
:::

#### Spruce budworm
::: {#exr-spruce_budworm}
In the spruce budworm model that you explored in the module Dynamical Systems,
$$\frac{du}{dt}=ru\left(1-\frac{u}{q}\right)-\frac{u^2}{1+u^2},$$
 suppose that the carrying capacity $q$ is fairly large
and that the growth rate $r$ assumes some value consistent with there being three
(non-zero) steady states. Suppose also that the population $u$ is at the outbreak
steady state $u_3$. Keeping $q$ fixed, imagine that $r$ is decreased
to a very small value. What happens to the population?
If $r$ is later restored to its original value, what does the
population tend to, and why?
:::

#### Wasps
::: {#exr-Hornet}
In a colony of the European Hornet there is a single queen that produces all the offspring. It
produces two kinds of offspring: workers and reproducers.
We'll denote the number of workers alive at time $t$ by $n(t)$ and the number of reproducers by $N(t)$.
The workers are responsible for collecting food. They can't breed themselves and they die in the winter. However
they are necessary to allow the queen to reproduce because without the food that they are collecting
the queen would have nothing to eat. So we need workers. But because they die in winter, they don't help the survival of the colony in the long run.
That's where the reproducers come in. They don't do any work, but they can, if they survive the winter, breed in the next spring as new queens.

So the queen now has a strategy of how to proceed:
It first of all needs to produce workers, and from time zero to time $t_c$ it only produces workers.
We assume that the birth rate is proportional to the number of workers,
so that the total birth rate of workers is $r n(t)$ for some constant $r>0$.
The queen then switches to producing only reproducers from time $t_c$ up to the start of winter at time $T$
and we assume that the total birth rate of reproducers is $R n(t)$ for some constant $R>0$.
We also assume that until the start of winter there are no deaths. 

What is the optimal  time $t_c$ at which the queen should switch from producing workers to producing reproducers
in order to achieve the largest number of producers $N(T)$ at the start of the winter and therefore to the largest
number of wasps in the following year.
:::

#### Wasps with death
::: {#exr-wasp_death}
In the wasp example from question 1, assume that the worker wasps die
at a constant per-capita rate $d$ but the reproducers do not die. 
Also assume that at time t=0 there is one worker, n(0)=1. Keep the birth rates as in @exr-Hornet.
Determine the number of workers $n(t)$ for any time between $t_c$ and $T$.
Determine the number of reproducers at the onset of winter at time $T$.
Derive the optimal time for the switchover time $t_c$.

:::


#### Modified Fibonacci
::: {#exr-fib_mod}
Modify Fibonacci's model for the population of rabbits that was discussed
in the lecture to model the case where at the end of each month some of the rabbits die, so that only a fraction $r$ of the pairs of rabbits that are alive in month $t$ survives to the next month. Assume
that reproduction takes place before this mortality and that the offspring all survive. Solve this to give the number $N_t$ of pairs after $t$ months given that initially
there are $c$ pairs. (Ignore the issue that fractional numbers of pairs don't really make sense, because if $c$ is large this fractional part makes little difference.)
:::

#### Discrete logistic model
::: {#exr-discrete_logistic}
 For some choices of the parameters, the discrete logistic model
$$N_{t+1}=rN_t\left(1-\frac{N_t}{K}\right)$$ 
can
lead to negative population numbers even when initially starting with a positive population below
its carrying capacity. Derive the condition on the parameters for this to happen. One good
way to approach this is to think about what the cobweb diagram would have to look like for
such a scenario.
:::

#### Discrete time model
::: {#exr-1.1}
Consider the discrete time model
$$N_{t+1}=\frac{rN_t}{1+(N_t/K)^b}$$
where $r$, $b$ and $K$ are positive parameters with $b>1$. Show that
the model has two steady states. Investigate the stability of the
trivial steady state. Show that the non-trivial steady state can lose
stability through a period doubling bifurcation at $b=2r/(r-1)$, or a
tangent bifurcation at $r=1$. Show also that, after a sufficient
amount of time,
$$\frac{Kr^2b^{b-1}(b-1)^{(b-1)/b}}{b^b+r^b(b-1)^{b-1}}\leq 
N_t\leq \frac{rK}{b}(b-1)^{(b-1)/b}.$$
:::

#### Sex ratio
::: {#exr-sex_ratio}
As in the lecture, consider the sex-structured population model
$$\frac{dF}{dt}=-\mu_F F+b_F\phi(F,M), ~~~\frac{dM}{dt}=-\mu_M M+b_M\phi(F,M),$$
where $F(t)$ denotes the number of females and $M(t)$ the number of males and $\mu_F,\mu_M,b_F,b_M$ are positive constants. Unlike in the lecture make the choice
$$\phi(F,N)=\sqrt{FM}.$$
Determine the asymptotic sex ratio.
::

#### Spotted Owl
::: {#exr-spotted_owl}
The Spotted Owl (Strix occidentalis) has the following population parameters:
$$m_a=\begin{cases}0&a<2\\m&a\geq 2\end{cases},~~~
l_2=l,~~l_{a+1}=p\, l_a \text{ if } a\geq 2.
$$
where $m_a$ is the number of females born, on average, to a female of age $a$, 
$l_a$ is the fraction of females surviving from birth to age $a$. Here $m,l$ and $p$ are
constants and age $a$ is integer valued.

We model the number $B_t$ of female births at time $t$ by the difference equation
$$
B_t=\sum_{a=2}^\infty B_{t-a}\,l_a\,m_a.
$$
Here the time $t$ and the age $a$ are integer valued.


a) Using the Ansatz $B_t=c\,\lambda^t$, show that this is a solution if $\lambda$ satisfies the equation
$\psi(\lambda)=1$, where
$$\psi(\lambda) = \sum_{a=2}^\infty \lambda^{-a}\,l_a\,m_a.$$

b) Use the formula for the geometric series to show that
$$\psi(\lambda)=\frac{l\,m}{\lambda(\lambda - p)}.$$

c) Solve the equation $\psi(\lambda)=1$ to find the possible values of $\lambda$ and use that
to write the general solution for $B_t$.

:::

#### Reaction-diffusion equation on strip
::: {#exr-1.9}
Consider the partial differential equation
$$
\frac{\partial u}{\partial t}=f(u)+D\frac{\partial^2u}{\partial x^2}
$$
where $f(0)=0$ and $f'(0)>0$. Assume that $u$ is small and show that
under this assumption the equation can be approximated by
$$
\frac{\partial u}{\partial t}=f'(0)\,u+D\frac{\partial^2u}{\partial x^2}.
$$
With Dirichlet type boundary conditions $u(0,t)=u(L,t)=0$ show that if
the population is not to be driven to extinction we must have
$L>\pi\sqrt{D/f'(0)}$.
:::

#### Age structured population
::: {#exr-age_structured}
In the age structured population model of section 2.1, show that if $b(a)=b$
and $\mu(a)=\mu$ are both constant then the condition for growth of the
population reduces to what you would expect.  For this purpose, start from the
equations of the age-structured model and the Ansatz $n(t,a)=e^{\gamma t}r(a)$ for unknown $r(a)$ and $\gamma$.
Give the expression for $r(a)$ in terms of $\gamma$. Calculate the expected number $\phi(0)$
of offspring that an individual produces during their lifetime. Then compare what this tells you about whether the
population goes extinct or explodes to the corresponding condition in the Malthus model.
:::

#### Age structured fish population
::: {#exr-age_structured_fish_population}
We model a fish population with the age structured population model of section 2.1. Let us assume that the birth rate is constant for all fish above a maturity age $a_m$ and zero for younger fish. Let us assume a constant natural mortality rate $\mu_0$.
Then impose a constant fishing mortality $\mu_f$ on all fish above maturity age.
What is the maximum value for the fishing mortality at which the population can
be maintained? What is the maximum sustainable yield?
:::

#### House finches
::: {#exr-finches}
_[Note: in this problem we combine a continuous time model for the dynamics within a single year with
a discrete model for the dynamics from one year to the next.
 The subscript $t \in \mathbb{Z}$ refers to the discrete year $t$, whereas
$\tau\in\mathbb{R}$ will indicate the continuous time within a single year.]_

A population of house finches resides in an isolated region in North America. 
In this problem you want to find out about the long-term prospects for the population.

Each year the
males and females begin their search for mates at the beginning of winter with a
combined population number $N_t$ in year $t$, and form $P_t$ breeding pairs by the end
of this search period, the start of the breeding season.

The mate search period lasts from within-year time $\tau = 0$ to the end of the search
period at within-year time $\tau = T$. Assume that there is a 1:1 sex ratio and that
males $M(\tau)$ and females $F(\tau)$ locate one another randomly to make a pair 
at rate $\sigma$, such that the number  $M(\tau)$ of males  that are not in a pair at time $\tau$ satisfies
$$\frac{dM}{d\tau}=-\sigma \,M\,F $$
and similarly  the number  $F$ of females  that are not in a pair at time $\tau$  satisfies
$$\frac{dF}{d\tau}=-\sigma \,M\,F. $$

You are given that the number of breeding pairs that establish a nest and breed
successfully is $G(P_t)P_t$, where the fraction $G(P_t)$ takes the particular form
$$G(P_t) = \frac{1}{1+P_t/\delta},$$
where $\delta$ represents the density of available nesting sites.
Each pair that reproduces successfully has a mean number $c$ of offspring.

The probability that a bird will survive from one year to the next is $s$.

a) Show that the number $n(\tau)=M(\tau)+F(\tau)$ of birds _not_ in a pair 
is governed by
$$\frac{dn}{d\tau}=-\frac{\sigma}{2}n^2, ~~~n(0)=N_t.$$

b) Using the above, show that the number $n(T)$ of birds that have not found a mate at the start of
the breeding season in year $t$ is
$$n(T)=\frac{r\,N_t}{r+2N_t}$$
where $N_t$ is the number of birds at the start of the season in that particular year and
where $r=4/(\sigma T)$.

c) Explain why the number of pairs $P(\tau)$ is governed by
$$\frac{dP}{d\tau}=-\frac12\frac{dn}{d\tau},~~~P(0)=0.$$

d) Use the above to show that the number of breeding pairs at the start of the
breeding season in year $t$ is 
$$P_t:=P(T)=\frac{N_t^2}{r+2N_t}.$$

e) Show that the population $N_{t+1}$ at the beginning of winter in year $t+1$ is given
by
$$
N_{t+1}=s\,N_t+\frac{c\,N_t^2}{r+2N_t+N_t^2/\delta}.
$$ {#eq-Nt}

f) Find the realistic steady states of the model in @eq-Nt for the case that
$$\frac{c}{1-s}-2\geq \sqrt{\frac{4r}{\delta}}.$$

g) Draw a cobweb diagram to illustrate the stability of the steady states in the case that there
are two positive steady states, labelling key features of the curves.

h) What type of bifurcation occurs when there is equality in the condition in part f)?

:::
